# fly.toml file generated for moveo on 2023-02-13T15:56:40+02:00

app = "moveo"
kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "moveo"
  MYSQL_USER = "tomer"

[build]
  image = "mysql:8"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = [
    "--default-authentication-plugin", "mysql_native_password",
    "--datadir", "/data/mysql",
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]

